import "./globals.css";

export const metadata = {
  title: "Aeroflix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="antialiased bg-gradient-radial bg-fixed bg-cover bg-center"
      >
        {children}
      </body>
    </html>
  );
}
